[package]
name = "birthdays"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
derive_more = { version = "2.1.1", features = ["display", "error"] }
grep = "0.4.1"
utils = { path = "../utils" }
walkdir = "2.5.0"
